# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
#pipileine > stages > Jobs > Tasks (steps)


jobs:
- job: job1
  steps:
  - script: echo Hello, world, JOb1!
    displayName: 'Run a one-line script'

- job: job2
  dependsOn: job1
  steps:
  - script: echo Hello, world, job2!
    displayName: 'Run a one-line script'
    condition: 


- job: job3
  dependsOn: job2
  steps:
  - script: echo Hello, world, Job3
    displayName: 'Run a one-line script'
