# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - job: firstJob
    steps: 
    - bash: echo first job
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: echo java -version
    - bash: echo node -version
    - bash: echo mvn -version
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

  - job: secondJob
    steps: 
    - bash: echo second job
- stage: DevDeploy
  jobs:
  - job: DevDeployJob
    steps: 
    - bash: echo Dev  job
- stage: QADeploy
  jobs:
  - job: QA_env_deploy
    steps: 
    - bash: echo QA deploy job
- stage: prodDeploy
  jobs:
  - job: Prod_Deploy
    steps: 
    - bash: echo Prod env job

